:set expandtab                                                                       
:set tabstop=4                                                                      
:retab                                                                              
:set shiftwidth=4                                                                    
:set hlsearch                                                                       
:set cursorline                                                                     
:set number                                                                          
:set nowrap                                                                         
:set colorcolumn=81

nmap <F8> :TagbarToggle<CR>
                                                                                     
:hi ColorColumn ctermbg=darkgrey guibg=darkgrey                                     
:hi CursorLine   cterm=NONE ctermbg=darkgrey guibg=darkgrey
:hi CursorColumn cterm=NONE ctermbg= darkgrey guibg=drakgrey
:nnoremap <Leader>c :set cursorline! cursorcolumn!<CR>
:nnoremap <silent> <F5> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar>:nohl<CR>

au BufNewFile,BufRead *.hb set filetype=xml
