:set expandtab                                                                       
:set tabstop=4                                                                      
:retab                                                                              
:set shiftwidth=4                                                                    
:set hlsearch                                                                       
:set cursorline                                                                     
:set number                                                                          
:set nowrap                                                                         
:set colorcolumn=121                                                                
                                                                                      
:hi ColorColumn ctermbg=darkgrey guibg=darkgrey                                     

:hi CursorLine   cterm=NONE ctermbg=darkgrey guibg=darkgrey
:hi CursorColumn cterm=NONE ctermbg= darkgrey guibg=drakgrey
:nnoremap <Leader>c :set cursorline! cursorcolumn!<CR>

au BufNewFile,BufRead *.hb set filetype=xml
