# The following variable defines the session which is started if the user doesn't explicitly select a session
# Source: http://svn.berlios.de/svnroot/repos/slim/trunk/xinitrc.sample

#DEFAULT_SESSION=startkde

#Check whether the external monitor is connected
xrandr | grep HDMI | grep " connected "

# 0 is returned on success
if [ $? -eq 0 ]; then
  xrandr --output LVDS --off --output HDMI-0 --mode 1920x1080
fi

case $1 in
xfce)
    xset +fp /usr/share/fonts/local
    xset fp rehash
	setxkbmap -layout gb
    exec ck-launch-session dbus-launch startxfce4
#    exec startxfce4 --with-ck-launch
    ;;
awesome)
    xset +fp /usr/share/fonts/local
    xset fp rehash
	setxkbmap -layout gb
    xcompmgr &
    exec ck-launch-session awesome
    ;;
*)
    xset +fp /usr/share/fonts/local
    xset fp rehash
 	setxkbmap -layout gb
    xcompmgr &
    exec ck-launch-session awesome
    ;;
esac


#exec ck-launch-session startkde
#exec ck-launch-session awesome
