#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# Merge in defaults and keymaps
[ -f $sysresources ] && /usr/bin/xrdb -merge $sysresources
[ -f $sysmodmap ] && /usr/bin/xmodmap $sysmodmap
[ -f $userresources ] && /usr/bin/xrdb -merge $userresources
[ -f $usermodmap ] && /usr/bin/xmodmap $usermodmap

# Check whether the external monitor is connected
xrandr | grep DVI | grep " connected "

# 0 is returned on success
if [ $? -eq 0 ]; then
  xrandr --output LVDS --off --output DVI-0 --mode 1920x1080
fi

xpmroot ~/images/01659_theearth_1920x1080.xpm &
setxkbmap -layout gb
trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 10 --transparent true --tint 0x191970 --height 12 &
xcompmgr &
xscreensaver -nosplash &
volwheel &
wicd-client &
# feh -FN /home/james/images/hebus_237161_1920x1080.jpg &

exec /usr/bin/xmonad

